project/reparacion/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, BooleanField, TextAreaField, SubmitField, SelectField, DateField, validators
from wtforms.validators import ValidationError, DataRequired, Length
from project.models import *

from wtforms.fields.html5 import DateField
from project import db

choices_detencion=[
	('10', '10 min'),
	('20', '20 min'), 
	('30', '30 min'),
	('45', '45 min'),
	('60', '1 hr'), 
	('90', '1,5 hrs'),
	('120', '2 hrs'),
	('150', '2,5 hrs'),
	('180', '3 hrs'),
	('210', '3,5 hrs'),
	('240', '4 hrs'),
	('270', '4,5 hrs'),
	('540','4,5 hasta todo el turno')
	]



class ReparacionForm(FlaskForm):
	maquina_id = SelectField('Maquina', coerce=int, validators = [DataRequired()])
	detencion_id= SelectField(
        'Tipo detencion',
        coerce=int, validators = [DataRequired()])
	duracion = SelectField(
        'Duracion detencion', choices = choices_detencion,
         validators = [DataRequired()])
	comentarios = TextAreaField('Comentarios (OPCIONAL)', validators=[Length(min=0, max=300)])
	created = DateField(u'Creacion (dd-mm-aaaa)', format='%Y-%m-%d')
	submit = SubmitField('Submit')

project/reparacion/__init__.py
#task/__init__.py

from flask import Blueprint

bp = Blueprint('reparacion', __name__)

from project.reparacion import routes

project/reparacion/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, session, request, jsonify
from flask_login import login_required, current_user
import flask_excel as excel


import json

from project.reparacion import bp
from project import db

from project.models import *
from .forms import ReparacionForm


@bp.route('/')
#@login_required
def list():
    reparaciones = Reparacion.query.all()
    return render_template('reparacion/list.html', reparaciones=reparaciones)


@bp.route('/reparacion', methods=['POST', 'GET'])
#@login_required
def add_reparacion():
    title = "Add Reparacion"
    form = ReparacionForm()
    form.maquina_id.choices = [(x.id, x.name) for x in Maquina.query.all()]
    form.detencion_id.choices = [(x.id, x.name) for x in Detencion.query.order_by(Detencion.name).all() ]
    if form.validate_on_submit():
        #content = request.form.get()
        reparacion = Reparacion()
        reparacion.maquina_id = form.maquina_id.data
        reparacion.detencion_id= form.detencion_id.data
        reparacion.duracion= int(form.duracion.data)
        reparacion.comentarios = form.comentarios.data
        reparacion.created = form.created.data
        db.session.add(reparacion)
        db.session.commit()
        return redirect(url_for('reparacion.list'))
    return render_template('reparacion/reparacion.html', title=title, form=form)


@bp.route('/modify/<int:reparacion_id>', methods=['GET', 'POST'])
#@login_required
def modify_reparacion(reparacion_id):
    title='Actualiza reparacion'
    test = Detencion.query.order_by(Detencion.name).all()
    reparacion = Reparacion.query.get(reparacion_id)
    form = ReparacionForm(obj=reparacion)
    form.maquina_id.choices = [(x.id, x.name) for x in Maquina.query.all()]
    form.detencion_id.choices = [(x.id, x.name) for x in Detencion.query.order_by(Detencion.name).all()]
    if form.validate_on_submit():
        #reparacion = request.form[form]
        reparacion.maquina_id = form.maquina_id.data
        reparacion.detencion_id= form.detencion_id.data
        reparacion.duracion = int(form.duracion.data)
        reparacion.comentarios = form.comentarios.data
        reparacion.created = form.created.data
        reparacion.modify = datetime.utcnow()
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('reparacion.list'))
    elif request.method == 'GET':
        form.populate_obj(reparacion)
        #form.content.data = task.content
        #form.maquina_id.data = task.maquina_id
    return render_template('reparacion/modify_reparacion.html', title=title, reparacion=reparacion,
        form=form)



@bp.route("/export", methods=['GET'])
def export():
    #filtered_task = Reparacion.query.filter_by(done=False).all()
    #column_names = ['id', 'content']
    #return excel.make_response_from_query_sets(filtered_task, column_names, "xls")
    return excel.make_response_from_tables(db.session, [Reparacion, Maquina], "xls")

project/templates/reparacion/list.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}


<p>Nueva detencion ? <a href="{{ url_for('reparacion.add_reparacion') }}">Crear</a></p>

{% if not current_user.is_anonymous %}
<p>Exportar a excel ? <a href="{{ url_for('reparacion.export') }}">Presione aquí</a></p>
{% endif %}


<table class="table">
<tr><th>Maquina</th>
   <th>Tipo</th>
    <th>Duracion (min)</th>
    <th>Fecha</th>
    <th>Comentarios</th>
       <th>Modificar</th>
  </tr>
  
  {% for reparacion in reparaciones %}
  <tr>
    <td>{{ reparacion.maquina}}</td>
    
    <td>  {{ reparacion.detencion }}</td>
    <td>{{ reparacion.duracion}}</td>

    <td>  {{ reparacion.created.strftime('%Y-%m-%d')  }}</td>
    <td>  {{ reparacion.comentarios }}</td>
        <td><a href="{{ url_for('reparacion.modify_reparacion', reparacion_id=reparacion.id ) }}">Editar</a> </td>
    </tr>
{% endfor %}
</table>

{% endblock content %}

project/templates/reparacion/modify_reparacion.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}


<form class="form" action="{{ url_for('reparacion.modify_reparacion', reparacion_id = reparacion.id) }}" method="post">

		{{ form.hidden_tag()  }}
	{% for field in form if field.type not in ["HiddenField", "CSRFTokenField"] %}
	<div class="form-group">
		{{ render_field(field) }}
	</div>
	{% endfor %}
</form>

{% endblock content %}

project/templates/reparacion/reparacion.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}


<form class="form" action="{{ url_for('reparacion.add_reparacion') }}" method="post">

		{{ form.hidden_tag()  }}
	{% for field in form if field.type not in ["HiddenField", "CSRFTokenField"] %}
	<div class="form-group">
		{{ render_field(field) }}
	</div>
	{% endfor %}
</form>

{% endblock content %}